// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseAlert: typeof import('./../components/BaseAlert.vue')['default']
    BaseButton: typeof import('./../components/BaseButton.vue')['default']
    BaseList: typeof import('./../components/BaseList.vue')['default']
    BaseLoader: typeof import('./../components/BaseLoader.vue')['default']
    BasePagination: typeof import('./../components/BasePagination.vue')['default']
    BasePlaceholder: typeof import('./../components/BasePlaceholder.vue')['default']
    BaseSearchInput: typeof import('./../components/BaseSearchInput.vue')['default']
    FEMAdviceSlip: typeof import('./../components/FEMAdviceSlip.vue')['default']
    FEMDropdown: typeof import('./../components/FEMDropdown.vue')['default']
    FEMNewsHomePage: typeof import('./../components/FEMNewsHomePage.vue')['default']
    FEMNotifications: typeof import('./../components/FEMNotifications.vue')['default']
    FEMRESTCountriesAPI: typeof import('./../components/FEMRESTCountriesAPI.vue')['default']
    FEMView: typeof import('./../components/FEMView.vue')['default']
    FooterView: typeof import('./../components/FooterView.vue')['default']
    HeaderView: typeof import('./../components/HeaderView.vue')['default']
    HomeView: typeof import('./../components/HomeView.vue')['default']
    IconChevronDown: typeof import('./../components/icons/IconChevronDown.vue')['default']
    IconCode: typeof import('./../components/icons/IconCode.vue')['default']
    IconDarkMode: typeof import('./../components/icons/IconDarkMode.vue')['default']
    IconDarkModeOutline: typeof import('./../components/icons/IconDarkModeOutline.vue')['default']
    IconDiscord: typeof import('./../components/icons/IconDiscord.vue')['default']
    IconFacebook: typeof import('./../components/icons/IconFacebook.vue')['default']
    IconGithub: typeof import('./../components/icons/IconGithub.vue')['default']
    IconLinkedIn: typeof import('./../components/icons/IconLinkedIn.vue')['default']
    IconSearch: typeof import('./../components/icons/IconSearch.vue')['default']
    IconSkype: typeof import('./../components/icons/IconSkype.vue')['default']
    IconWavingHand: typeof import('./../components/icons/IconWavingHand.vue')['default']
    MainView: typeof import('./../components/MainView.vue')['default']
    MatchingPairView: typeof import('./../components/MatchingPairView.vue')['default']
    MdiAlertCircle: typeof import('./../components/icons/MdiAlertCircle.vue')['default']
    MdiAlertOctagon: typeof import('./../components/icons/MdiAlertOctagon.vue')['default']
    MdiCheckCircle: typeof import('./../components/icons/MdiCheckCircle.vue')['default']
    MdiInformation: typeof import('./../components/icons/MdiInformation.vue')['default']
    NotFoundView: typeof import('./../components/NotFoundView.vue')['default']
    ParticlesView: typeof import('./../components/ParticlesView.vue')['default']
    PhWarningCircle: typeof import('./../components/icons/PhWarningCircle.vue')['default']
    PlaygroundView: typeof import('./../components/PlaygroundView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TetrisView: typeof import('./../components/TetrisView.vue')['default']
  }
}
